### ISSUE TITLE
Thread-safety support

### ISSUE THREAD

**Issue by ShivKJ** [metteo/jts#17]
Hi,
Is this library thread safe?

I have a MULTILINESTRING and I am trying to find its intersection with other LineString. As the number of LineString is hugh, I am thinking of processing it parallelly.
Can I use this lib in multiprocessing environment?

**Comment by metteo** [comment]
Hi

I think it should be possible to split the multi geom into separate geoms and process them concurrently.

However, I would advice usage of the main fork found here: https://github.com/locationtech/jts You can ask there as well - they have label `type-question`

This fork was created when the main one was still in SVN on sourceforge. Now the main one is also on github and actively maintained so it's better to use that one.

**Comment by ShivKJ** [comment]
Ok.
Thanks.
